import { Router } from "express";
import { AccountController } from "../controller/accounts.controller";
import { authenticateJWT } from "../middleware/auth";
import { upload } from "../utils/upload";

const route = Router()


route.get("/client/home", authenticateJWT, AccountController.clientHome)
route.get("/allUsers", authenticateJWT, AccountController.getAllUsers)
route.put("/admin/ban/:id", authenticateJWT, AccountController.toggleIsBan)
route.post("/adminMessage", authenticateJWT,upload.single('file') ,AccountController.submitAdminMessage) 
route.get("/adminMessage/unseen", authenticateJWT, AccountController.getAdminMessageUnseen)
route.get("/adminMessage", authenticateJWT, AccountController.getAdminMessage)
route.get("/admin", authenticateJWT, AccountController.getAdminAccount) 
route.get("/clients", authenticateJWT, AccountController.getClientsAccount)
route.get("/exists", authenticateJWT, AccountController.checkEmailExists)
route.get("/bussinessInfo/:id", authenticateJWT, AccountController.getBussinessInfo)
route.get("/artistInfo/:id", authenticateJWT, AccountController.getArtistInfo)
route.post("/accountInfo/imgUpload", authenticateJWT, upload.single('file') ,AccountController.uploadProfileInfoImg)
route.post("/changeProfilePic", authenticateJWT, upload.single('file') ,AccountController.changePofilePicture)
route.post("/review", authenticateJWT, upload.single('file') ,AccountController.placeReview)
route.post("/artistVerification/submit", authenticateJWT,upload.single('file') ,AccountController.submitArtistVerification)
route.post("/BussinessVerification/submit", authenticateJWT, upload.fields(([{ name: 'BarangayClearance', maxCount: 1 },{ name: 'businessPermit', maxCount: 1 }])) ,AccountController.submitBussinessVerification)
route.post("/artistVerification/admin", authenticateJWT, AccountController.artistVerification)
route.post("/bussinessVerification/admin", authenticateJWT, AccountController.bussinessVerification)
route.get("/artistVerification", authenticateJWT, AccountController.getAllArtistVerification)
route.put("/location/:id", authenticateJWT, AccountController.updateArtistLocation)
route.get("/artistInfo", AccountController.getAllArtistInfo)
route.get("/bussinessInfo", authenticateJWT, AccountController.getAllBussinessInfo)
route.post("/role", authenticateJWT, AccountController.addRole)
route.get("/artistApplication/:id", authenticateJWT, AccountController.getArtistApplicationByBussiness)
route.post("/artistApplyToBussiness/:id", authenticateJWT, AccountController.artistApplyToBussiness)
route.post("/applicationApproval", authenticateJWT, AccountController.artistApplicationApproval)
route.get("/transaction/sender/:id", authenticateJWT, AccountController.getSenderTransactions)
route.get("/transaction/receiver/:id", authenticateJWT, AccountController.getReceiverTransactions)
route.get("/transaction/:id/receipt", authenticateJWT, AccountController.getTransactionReceipt)
route.get("/artistBussiness/:id", authenticateJWT, AccountController.getArtistBussiness)
route.get("/notifications/unseen", authenticateJWT, AccountController.getAccountNotificationUnseen)
route.get("/notifications/:id", authenticateJWT, AccountController.getAccountNotifications)
route.put("/employee/info", authenticateJWT, AccountController.updateEmployeeInfo)  
route.put("/employee/remove", authenticateJWT, AccountController.removeEmployee)  
route.post("/add/employee", authenticateJWT, AccountController.addEmployee)  
route.get("/employee/:email", authenticateJWT, AccountController.getEmployee)    
route.put("/employee/role", authenticateJWT, AccountController.EditEmployeeRole)  
route.put("/schedule", authenticateJWT, AccountController.editSchedule) 
route.post("/expencess", authenticateJWT, AccountController.addExpencess) 
route.post("/attendance/leave", authenticateJWT ,AccountController.createBusinessLeave) 
route.put("/attendance/leave", authenticateJWT, AccountController.leaveAction)
route.get("/attendance/leave", authenticateJWT, AccountController.getBusinessLeave)
route.get("/attendance/:email", authenticateJWT, AccountController.getAccountAttendance) 
route.get("/attendance", authenticateJWT, AccountController.getBussinessAttendance) 
route.post("/attendance/timeIn", authenticateJWT, AccountController.timeInAttendance) 
route.post("/attendance/timeOut", authenticateJWT, AccountController.timeOutAttendance) 
route.post("/attendance/ot", authenticateJWT, AccountController.handleOt) 
route.post("/aiAutoFill", authenticateJWT,  upload.single('file'), AccountController.AiAutoFill) 
route.get("/expencess/:id", authenticateJWT, AccountController.getBussinessFinance) 
route.get("/:id", authenticateJWT, AccountController.getAccount)    
route.post("/payroll", authenticateJWT, AccountController.createPayroll) 
route.get("/payroll/:id", authenticateJWT, AccountController.getBussinessPayroll) 
route.get("/payslip/:bussiness/:email", authenticateJWT, AccountController.getPayslip) 
route.put("/payroll/approve", authenticateJWT, AccountController.approvePayroll) 
route.put("/payroll/reject/:id", authenticateJWT, AccountController.rejectPayroll)
route.put("/payroll/proof", authenticateJWT,upload.single('file') ,AccountController.submitPayslipProof) 
route.put("/documents", authenticateJWT,upload.single('file') ,AccountController.documentSubmit) 
route.get("/document/:id", authenticateJWT, AccountController.getDocuments) 
route.put("/freeTrial/:id", authenticateJWT, AccountController.startTrial) 
route.post("/subscribe/payment", authenticateJWT, AccountController.subsPayment) 
route.put("/config/:id", authenticateJWT, AccountController.editConfig) 
route.put("/jobpost", authenticateJWT, AccountController.jobPost) 
route.get("/dashboard/:id/:month", authenticateJWT, AccountController.getBussinessDashboard)




export default route