location ^~ /api/create-checkout-session {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://nextjs;
}


location = /api/admin         { return 404; }
location = /api/artistAccount { return 404; }
location = /api/addField      { return 404; }

location /api/ {
    include /etc/nginx/snippets/proxy.conf;
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;
    proxy_pass http://express/;
}

location / {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://nextjs;
}
